Test go to cd 2

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -19,7 +19,8 @@ jobs:
         run: sudo apt-get install -y sshpass
       - name: SSH into server
         run: |
-          sshpass -p ${{ secrets.SERVER_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} -p 3000 <<EOF cd /home/server_admin/dp/pemsa/back/service_9000_datamw/
+          sshpass -p ${{ secrets.SERVER_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} -p 3000 <<EOF 
+            cd /home/server_admin/dp/pemsa/back/service_9000_datamw/ 2>&1 || echo "Error al cambiar de directorio: \$?"
             touch example.txt
             docker login ghcr.io -u pemsa-devbk -p ${{ secrets.TOKEN_DEPLOY }}
             docker pull ghcr.io/pemsa-devbk/rpc-mw/rpc-mw:latest
